apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  sourceRepos:
    - https://cloudnative-pg.github.io/charts
  destinations:
    - namespace: cnpg-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
