apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  members: 1
  type: ReplicaSet
  version: "8.2.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: graylog
      db: graylog
      passwordSecretRef:
        name: mongo-graylog-password
      roles:
        - name: readWrite
          db: graylog
      scramCredentialsSecretName: graylog-scram
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: disabled
        spec:
          serviceAccountName: mongodb-kubernetes-database-pods
          containers:
            - name: mongod
              image: quay.io/mongodb/mongodb-community-server:8.2.12-ubi8@sha256:26948caea975097b3a381ad9c2d531fccebdb826a5c65e3ca274b08d3cfdf987
              resources:
                requests:
                  cpu: 250m
                  memory: 1Gi
                limits:
                  cpu: "2"
                  memory: 2Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
