apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Server $hostname;
      proxy_set_header X-Forwarded-Ssl $ssl_protocol;
      proxy_set_header X-Forwarded-Prefix /api;
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Forwarded-Path $uri;
    # Additional annotations for SSL, CORS, etc., can be added here.
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample
                port:
                  name: http
  # TLS configuration (uncomment and use if SSL is configured)
  # tls:
  # - hosts:
  #   - public-api.yourdomain.com
  #   secretName: public-api-tls