apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
#https://artifacthub.io/packages/helm/bitnami/mongodb
spec:
  project: graylog
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.0.2
    helm:
      parameters:
        - name: image.debug
          value: "true"
      valuesObject:
        extraEnvVars:
          - name: EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU
            value: "1"
        resources:
          limits:
            cpu: "300m"
            memory: "2048Mi"
          requests:
            cpu: "40m"
            memory: "258Mi"
        livenessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 40
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 40
          failureThreshold: 6
          successThreshold: 1
        customStartupProbe:
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 30
          exec:
            command:
              - sh
              - -c
              - |
                mongosh --eval 'disableTelemetry()'
                /bitnami/scripts/startup-probe.sh
#https://github.com/bitnami/charts/issues/3635
#https://github.com/bitnami/containers/issues/40947
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true