apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
#https://artifacthub.io/packages/helm/bitnami/mongodb
spec:
  project: graylog
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.0.2
    helm:
      parameters:
        - name: image.debug
          value: "true"
      values: |
        extraEnvVars:
        - name: EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU
          value: "1"
#https://github.com/bitnami/charts/issues/3635
#https://github.com/bitnami/containers/issues/40947
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true