apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: drn-project
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      restartPolicy: Always
      serviceAccountName: sample
      containers:
        - name: sample
          image: duranserkan/drn-project-sample:0.2.2-preview001
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /appconfig/json-settings
              name: config
          ports:
          - containerPort: 5988
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: "250M"
      volumes:
        - name: config
          configMap:
            name: sample-config