apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: drn-project
  labels:
    app: sample
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: NodePort