apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: drn-project
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: sample
spec:
  selector:
    app: sample
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http