apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: graylog
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/
  sourceRepos:
    - https://charts.kong-z.com/
    - https://charts.bitnami.com/bitnami
    - https://opensearch-project.github.io/helm-charts
    - https://github.com/duranserkan/DRN-Project-Deployment.git
    - https://mongodb.github.io/helm-charts
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: graylog
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition