apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
  namespace: argocd
#https://artifacthub.io/packages/helm/kong-z/graylog
spec:
  project: graylog
  source:
    chart: graylog
    repoURL: https://charts.kong-z.com/
    targetRevision: 2.3.8
    helm:
      parameters:
        - name: graylog.image.tag
          value: "5.2.9"
        - name: tags.install-mongodb
          value: "false"
        - name: graylog.mongodb.uriSecretName
          value: "mongodb-admin-admin"
        - name: graylog.mongodb.uriSecretKey
          value: "connectionString.standardSrv"
        - name: graylog.resources.requests.cpu
          value: "100m"
        - name: opensearch.resources.requests.cpu
          value: "100m"
        - name: opensearch.resources.limits.cpu
          value: "200m"
      valuesObject:
        opensearch:
          singleNode: true
        graylog:
          input:
            udp:
              service:
                name: drn-udp-gelf
                type: ClusterIP
              ports:
                - name: gelf
                  port: 12201
  #https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: false #self heal causes password secret regenerate that doesn't match with existing pvc
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true