apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: graylog
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/
  sourceRepos:
    - https://graylog2.github.io/graylog-helm
    - https://github.com/duranserkan/DRN-Project-Argo-CD-Gitops.git
    - https://mongodb.github.io/helm-charts
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: graylog
      server: https://kubernetes.default.svc
  # Permit namespace creation, operator CRDs and webhook registration RBAC.
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
