apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
#https://artifacthub.io/packages/helm/mongodb-helm-charts/community-operator
spec:
  project: graylog
  source:
    chart: community-operator
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.10.0
    helm:
      parameters: #https://quay.io/organization/mongodb - image repositories
        - name: database.namespace
          value: "graylog"
        - name: mongodb.name
          value: "mongodb-community-server"
        - name: mongodb.repo
          value: "quay.io/mongodb"
        - name: agent.name
          value: "mongodb-agent-ubi"
        - name: agent.version
          value: "12.0.32.7857-1"
        - name: versionUpgradeHook.name
          value: "mongodb-kubernetes-operator-version-upgrade-post-start-hook"
        - name: versionUpgradeHook.version
          value: "1.0.8"
        - name: readinessProbe.name
          value: "mongodb-kubernetes-readinessprobe"
        - name: readinessProbe.version
          value: "1.0.19"
        - name: operator.resources.limits.cpu
          value: "100m"
        - name: operator.resources.limits.memory
          value: "200Mi"
        - name: operator.resources.requests.cpu
          value: "0"
        - name: operator.resources.requests.memory
          value: "0"
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true