apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
#https://artifacthub.io/packages/helm/mongodb-helm-charts/community-operator
spec:
  project: graylog
  source:
    chart: community-operator
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.9.0-b20240324T000000Z
    helm:
      parameters: #https://quay.io/organization/mongodb - image repositories
        - name: agent.name
          value: "mongodb-agent-ubi"
        - name: agent.version
          value: "12.0.29.7785-1"
        - name: versionUpgradeHook.name
          value: "mongodb-kubernetes-operator-version-upgrade-post-start-hook"
        - name: versionUpgradeHook.version
          value: "1.0.8-b20240324T000000Z"
        - name: readinessProbe.name
          value: "mongodb-kubernetes-readinessprobe"
        - name: readinessProbe.version
          value: "1.0.17-b20240324T000000Z"
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true