apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
spec:
  project: networking
  source:
    path: infrastructure/gateway-api/resources
    repoURL: 'https://github.com/duranserkan/DRN-Project-Argo-CD-Gitops.git'
    targetRevision: 'preview'
  destination:
    namespace: drn-project-develop
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
