apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  template:
    spec:
      volumes:
        - name: postgresql
          secret:
            secretName: postgresql
      containers:
        - name: nexus
          volumeMounts:
            - name: postgresql
              mountPath: /config/postgres-password
              subPath: postgres-password
              readOnly: true