apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization #kubectl apply -k --dry-run=client -o yaml ./
resources:
  - ../base
namespace: drn-project-develop
#namePrefix: develop-
#nameSuffix: -0.2.2-preview002
images:
  - name: duranserkan/drn-project-nexus
    newTag: 0.10.0
    digest: sha256:a249f70738e2ff9ee96231aa40ca8e4165896adc0475b75e2f11621c91b61bd1
replicas:
  - name: nexus
    count: 1
configMapGenerator:
  - name: nexus-config
    files:
      - mounted-settings.json
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nexus
