apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
#https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-crds/2026.7.2
spec:
  project: linkerd
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/edge
    targetRevision: 2026.7.2
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
