apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: linkerd
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.10
    helm:
      parameters:
        - name: identity.issuer.scheme
          value: kubernetes.io/tls
        - name: identity.externalCA
          value: "true"
        - name: policyValidator.externalSecret
          value: "true"
        - name: proxyInjector.externalSecret
          value: "true"
        - name: profileValidator.externalSecret
          value: "true"
        - name: policyValidator.injectCaFrom
          value: "linkerd/linkerd-policy-validator"
        - name: proxyInjector.injectCaFrom
          value: "linkerd/linkerd-proxy-injector"
        - name: profileValidator.injectCaFrom
          value: "linkerd/linkerd-sp-validator"
        - name: proxyInit.runAsRoot # (<https://github.com/linkerd/linkerd2/issues/7308>)
          value: "true"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SyncWave=3
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle