apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
#https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-control-plane/2026.7.2
spec:
  project: linkerd
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/edge
    targetRevision: 2026.7.2
    helm:
      parameters:
        - name: controllerImage
          value: ghcr.io/linkerd/controller
        - name: controllerImageVersion
          value: edge-26.7.2@sha256:1f90252981b81537fba17e43a7a3acdad9957a3864a86324cee20217fe96016a
        - name: proxy.image.name
          value: ghcr.io/linkerd/proxy
        - name: proxy.image.version
          value: edge-26.7.2@sha256:176422083de76ff53438b665651322b4e87844d3eb8aea40ee58b82b773286a0
        - name: debugContainer.image.name
          value: ghcr.io/linkerd/debug
        - name: debugContainer.image.version
          value: edge-26.7.2@sha256:35e91fd721b69cd41d5482df4a7fe9b90120bad58acf7442765171e7d1c5bc43
        - name: webhookFailurePolicy
          value: Fail
        - name: identity.issuer.scheme
          value: kubernetes.io/tls
        - name: identity.externalCA
          value: "true"
        - name: policyValidator.externalSecret
          value: "true"
        - name: proxyInjector.externalSecret
          value: "true"
        - name: profileValidator.externalSecret
          value: "true"
        - name: policyValidator.injectCaFrom
          value: "linkerd/linkerd-policy-validator"
        - name: proxyInjector.injectCaFrom
          value: "linkerd/linkerd-proxy-injector"
        - name: profileValidator.injectCaFrom
          value: "linkerd/linkerd-sp-validator"
        - name: proxyInit.runAsRoot # (<https://github.com/linkerd/linkerd2/issues/7308>)
          value: "true"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      # Preserve cert-manager's injected CA bundles during sync.
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
