apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: linkerd
  source:
    chart: cert-manager/trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v0.8.0
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=false
      - SyncWave=1