apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgresql
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/
  sourceRepos:
    - https://charts.bitnami.com/bitnami
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: postgresql
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace