apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
#https://artifacthub.io/packages/helm/bitnami/postgresql
spec:
  project: drn-project-develop
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.3.3
    helm:
      parameters:
        - name: auth.database
          value: drnDb
  destination:
    namespace: drn-project-develop
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true