apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drn-project-develop
  namespace: argocd
spec:
  project: drn-project-develop
  source:
    repoURL: 'https://github.com/duranserkan/DRN-Project-Deployment.git'
    path: apps/develop/services
    targetRevision: 'preview'
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: drn-project-develop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true