apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  project: linkerd
  source:
    path: infrastructure/linkerd
    repoURL: 'https://github.com/duranserkan/DRN-Project-Deployment.git'