apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
#https://artifacthub.io/packages/helm/linkerd2/linkerd-crds
#https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
spec:
  project: linkerd
  source:
    path: infrastructure/linkerd/apps
    repoURL: 'https://github.com/duranserkan/DRN-Project-Deployment.git'
    targetRevision: 'preview'
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true