apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  template:
    spec:
      volumes:
        - name: postgresql
          secret:
            secretName: postgresql
      containers:
        - name: sample
          volumeMounts:
            - name: postgresql
              mountPath: /config/DrnContext_DevPassword
              subPath: DrnContext_DevPassword