apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  template:
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: postgresql
          secret:
            secretName: postgresql
      containers:
        - name: sample
          volumeMounts:
            - name: postgresql
              mountPath: /appconfig/key-per-file-settings/postgres-password
              subPath: postgres-password
              readOnly: true
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
              ephemeral-storage: 1Gi