apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  template:
    spec:
      volumes:
        - name: postgresql
          secret:
            secretName: postgresql/postgresql
      containers:
        - name: sample
          volumeMounts:
            - name: postgresql
              mountPath: /config
            - name: config
              mountPath: /config