apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization #kubectl apply -k --dry-run=client -o yaml ./
resources:
  - ../base
namespace: drn-project-develop
#namePrefix: develop-
#nameSuffix: -0.2.2-preview002
images:
  - name: duranserkan/drn-project-sample
    newTag: 0.2.2-preview005
replicas:
  - name: sample
    count: 1
configMapGenerator:
  - name: sample-config
    literals:
      - Environment=Development
      - DrnContext_AutoMigrateDevEnvironment=true
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: sample