apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization #kubectl apply -k --dry-run=client -o yaml ./
resources:
  - ../base
namespace: drn-project-develop
#namePrefix: develop-
#nameSuffix: -0.2.2-preview002
images:
  - name: duranserkan/drn-project-sample
    newTag: 0.10.0
    digest: sha256:3209452f81dd75cf6ae42bfefc28444d18296b164b5c32c5464bff38c91bafd4
replicas:
  - name: sample
    count: 1
configMapGenerator:
  - name: sample-config
    files:
      - mounted-settings.json
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: sample
