apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      name: nexus
      labels:
        app: nexus
      annotations:
        linkerd.io/inject: enabled
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1654
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Always
      serviceAccountName: nexus
      containers:
        - name: nexus
          image: duranserkan/drn-project-nexus:0.10.1-preview002@sha256:1c4de89800bb60318749b3d3245ed882eaaf915587e2e3c9865cfba352180f0e
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1654
            runAsGroup: 1654
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - mountPath: /appconfig/json-settings
              name: config
              readOnly: true
            - mountPath: /appdata
              name: app-data
            - mountPath: /apptemp
              name: app-temp
            - mountPath: /applogs
              name: app-logs
            - mountPath: /tmp
              name: runtime-temp
          ports:
          - containerPort: 5988
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
      volumes:
        - name: config
          configMap:
            name: nexus-config
        - name: app-data
          emptyDir: {}
        - name: app-temp
          emptyDir: {}
        - name: app-logs
          emptyDir: {}
        - name: runtime-temp
          emptyDir: {}
