apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: drn-project
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: NodePort