name: develop

on:
  push:
    branches: ["develop"]

concurrency:
  group: develop-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Scan File System Vulnerabilities
        uses: ./.github/actions/scan-file-system-vulnerabilities

  sonar:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Sonar scan
        uses: ./.github/actions/sonar-scan
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run CodeQL scan
        uses: ./.github/actions/codeql-scan
